version: "3.9"
services:
  php-apache:
    ports:
      - "8080:80"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
  mysql:
    ports:
      - "3307:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "proiectqwerty"
      MYSQL_DATABASE: "proiectosa"
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData:
